export const CSS = String.raw`
.niv-root{position:fixed;inset:0;z-index:1000;display:grid;grid-template-rows:58px minmax(0,1fr);pointer-events:auto;background:var(--dsw-alias-bg-base,#101113);color:var(--dsw-alias-label-primary);outline:0}
.niv-topbar{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:8px 14px;border-bottom:1px solid var(--dsw-alias-border-l2);background:color-mix(in srgb,var(--dsw-alias-bg-base,#101113) 94%,transparent);backdrop-filter:blur(18px)}
.niv-title{display:flex;min-width:0;flex-direction:column}.niv-title strong{overflow:hidden;font-size:13px;font-weight:600;line-height:20px;text-overflow:ellipsis;white-space:nowrap}.niv-title small{color:var(--dsw-alias-label-tertiary);font-size:11px;line-height:17px}
.niv-actions{display:flex;align-items:center;gap:4px}.niv-button,.niv-download{box-sizing:border-box;display:inline-flex;align-items:center;justify-content:center;gap:6px;height:32px;padding:0 10px;border:1px solid transparent;border-radius:999px;background:transparent;color:var(--dsw-alias-label-primary);font:inherit;font-size:12px;text-decoration:none;white-space:nowrap;cursor:pointer}.niv-button:hover,.niv-download:hover,.niv-button[data-active=true]{background:var(--dsw-alias-interactive-bg-hover)}.niv-button:focus-visible,.niv-download:focus-visible{outline:2px solid var(--dsw-alias-border-l3);outline-offset:1px}.niv-button:disabled{opacity:.38;cursor:default}.niv-icon-only{width:32px;padding:0}.niv-zoom{min-width:46px;color:var(--dsw-alias-label-secondary);font-variant-numeric:tabular-nums}
.niv-workspace{position:relative;display:grid;min-height:0;grid-template-columns:minmax(0,1fr)}.niv-workspace[data-sidebar=true]{grid-template-columns:minmax(0,1fr) 300px}
.niv-stage{position:relative;display:grid;place-items:center;min-width:0;min-height:0;overflow:hidden;padding:28px;background:var(--dsw-alias-bg-base,#101113);touch-action:none;user-select:none}.niv-stage[data-dragging=true]{cursor:grabbing}.niv-stage[data-annotating=true]{cursor:crosshair}
.niv-surface{position:relative;display:inline-flex;max-width:100%;max-height:100%;transform-origin:center;will-change:transform}.niv-image{display:block;max-width:calc(100vw - 56px);max-height:calc(100vh - 114px);border-radius:12px;object-fit:contain;box-shadow:var(--dsw-shadow-lv3);user-select:none;-webkit-user-drag:none}
.niv-pin{position:absolute;display:grid;place-items:center;width:24px;height:24px;padding:0;border:2px solid var(--dsw-alias-label-primary-inverted,#fff);border-radius:50%;background:var(--dsw-alias-label-primary);box-shadow:var(--dsw-shadow-lv2);color:var(--dsw-alias-bg-base,#101113);font:inherit;font-size:11px;font-weight:700;cursor:pointer}.niv-pin[data-active=true]{background:var(--dsw-alias-state-business-primary,#3964fe);color:#fff}
.niv-nav{position:absolute;top:50%;z-index:2;width:38px;height:38px;padding:0;transform:translateY(-50%);background:var(--dsw-alias-button-floating-fill);box-shadow:var(--dsw-shadow-lv2)}.niv-prev{left:18px}.niv-next{right:18px}.niv-counter{position:absolute;bottom:16px;left:50%;padding:5px 10px;border-radius:999px;background:var(--dsw-alias-button-floating-fill);color:var(--dsw-alias-label-secondary);font-size:11px;transform:translateX(-50%)}
.niv-hint{position:absolute;bottom:16px;left:50%;padding:6px 10px;border-radius:999px;background:var(--dsw-alias-button-floating-fill);box-shadow:var(--dsw-shadow-lv2);color:var(--dsw-alias-label-secondary);font-size:11px;transform:translateX(-50%)}
.niv-sidebar{display:flex;min-width:0;flex-direction:column;overflow:hidden;border-left:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-2,var(--dsw-alias-bg-base))}.niv-sidebar-head{display:flex;align-items:flex-start;justify-content:space-between;gap:10px;padding:16px 14px 10px}.niv-sidebar-head div{display:flex;min-width:0;flex-direction:column}.niv-sidebar-head strong{font-size:13px;line-height:20px}.niv-sidebar-head small{color:var(--dsw-alias-label-tertiary);font-size:11px;line-height:17px}.niv-note-list{display:flex;min-height:0;flex:1;flex-direction:column;gap:8px;overflow:auto;padding:0 12px 12px}.niv-note{display:grid;grid-template-columns:24px minmax(0,1fr) 24px;align-items:start;gap:7px;padding:9px;border:1px solid var(--dsw-alias-border-l2);border-radius:12px;background:var(--dsw-alias-bg-layer-3)}.niv-note[data-active=true]{border-color:var(--dsw-alias-state-business-primary,#3964fe)}.niv-note-index{display:grid;place-items:center;width:22px;height:22px;border-radius:50%;background:var(--dsw-alias-label-primary);color:var(--dsw-alias-bg-base,#101113);font-size:10px;font-weight:700}.niv-note textarea{box-sizing:border-box;width:100%;min-height:64px;resize:vertical;border:0;outline:0;background:transparent;color:var(--dsw-alias-label-primary);font:inherit;font-size:12px;line-height:18px}.niv-note textarea::placeholder{color:var(--dsw-alias-label-dimmed)}.niv-note-remove{width:22px;height:22px;padding:0}.niv-sidebar-empty{padding:8px 14px;color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:18px}.niv-sidebar-foot{display:flex;justify-content:flex-end;padding:10px 12px;border-top:1px solid var(--dsw-alias-border-l2)}
.niv-editor{position:absolute;right:0;bottom:0;left:0;z-index:3;display:flex;align-items:center;gap:8px;padding:10px 14px;border-top:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-2,var(--dsw-alias-bg-base))}.niv-editor input{min-width:0;flex:1}.niv-editor-error{color:var(--dsw-alias-state-error-primary);font-size:11px}.niv-workspace[data-editor=true] .niv-stage{padding-bottom:82px}
@media(max-width:760px){.niv-root{grid-template-rows:auto minmax(0,1fr)}.niv-topbar{align-items:flex-start;flex-direction:column;gap:6px}.niv-actions{width:100%;overflow-x:auto;padding-bottom:2px}.niv-workspace[data-sidebar=true]{grid-template-columns:minmax(0,1fr);grid-template-rows:minmax(0,1fr) minmax(128px,34vh)}.niv-sidebar{border-top:1px solid var(--dsw-alias-border-l2);border-left:0}.niv-stage{padding:12px}.niv-image{max-width:calc(100vw - 24px);max-height:calc(100vh - 178px)}.niv-editor{align-items:stretch;flex-direction:column}.niv-editor button{width:100%}.niv-workspace[data-editor=true] .niv-stage{padding-bottom:122px}.niv-button span.niv-label{display:none}}
@media(prefers-reduced-motion:reduce){.niv-surface{transition:none}}
`
